/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sis_inf_2;

import static java.awt.Color.black;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author CORE i5
 */
public class CrearCuenta extends javax.swing.JPanel {

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
    }
    
    public boolean isEmail(String correo){
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(correo);
        if(mat.find()){
            return true;
        }else{
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenidoInferior = new javax.swing.JPanel();
        lblRegistrate = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblConfContraseña = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        TextFieldUsuario = new javax.swing.JTextField();
        TextFieldCorreo = new javax.swing.JTextField();
        PasswordFieldContraseña = new javax.swing.JPasswordField();
        PasswordFieldContraseñaConf = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        btnRegistrarse = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContenidoInferior.setBackground(new java.awt.Color(153, 204, 255));
        ContenidoInferior.setOpaque(false);

        lblRegistrate.setFont(new java.awt.Font("Roboto", 2, 48)); // NOI18N
        lblRegistrate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrate.setText("Registrate");

        lblNombre.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        lblUsuario.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        lblUsuario.setText("Usuario:");

        lblContraseña.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        lblContraseña.setText("Contraseña:");

        lblConfContraseña.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        lblConfContraseña.setText("Confirmar Contraseña:");

        lblCorreo.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        lblCorreo.setText("Correo electronico:");

        TextFieldNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TextFieldNombre.setForeground(new java.awt.Color(204, 204, 204));
        TextFieldNombre.setText("Ingrese su nombre");
        TextFieldNombre.setToolTipText("");
        TextFieldNombre.setActionCommand("<Not Set>");
        TextFieldNombre.setBorder(null);
        TextFieldNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldNombreMouseClicked(evt);
            }
        });
        TextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreActionPerformed(evt);
            }
        });

        TextFieldUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TextFieldUsuario.setForeground(new java.awt.Color(204, 204, 204));
        TextFieldUsuario.setText("Ingrese su nombre de Usuario");
        TextFieldUsuario.setToolTipText("");
        TextFieldUsuario.setActionCommand("<Not Set>");
        TextFieldUsuario.setBorder(null);
        TextFieldUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldUsuarioMouseClicked(evt);
            }
        });
        TextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldUsuarioActionPerformed(evt);
            }
        });

        TextFieldCorreo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TextFieldCorreo.setForeground(new java.awt.Color(204, 204, 204));
        TextFieldCorreo.setText("Ingrese su correo electronico");
        TextFieldCorreo.setToolTipText("");
        TextFieldCorreo.setActionCommand("<Not Set>");
        TextFieldCorreo.setBorder(null);
        TextFieldCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldCorreoFocusLost(evt);
            }
        });
        TextFieldCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldCorreoMouseClicked(evt);
            }
        });
        TextFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCorreoActionPerformed(evt);
            }
        });

        PasswordFieldContraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        PasswordFieldContraseña.setForeground(new java.awt.Color(204, 204, 204));
        PasswordFieldContraseña.setText("00000000");
        PasswordFieldContraseña.setBorder(null);
        PasswordFieldContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordFieldContraseñaMouseClicked(evt);
            }
        });

        PasswordFieldContraseñaConf.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        PasswordFieldContraseñaConf.setForeground(new java.awt.Color(204, 204, 204));
        PasswordFieldContraseñaConf.setText("00000000");
        PasswordFieldContraseñaConf.setBorder(null);
        PasswordFieldContraseñaConf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordFieldContraseñaConfMouseClicked(evt);
            }
        });
        PasswordFieldContraseñaConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldContraseñaConfActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        btnRegistrarse.setBackground(new java.awt.Color(102, 102, 102));
        btnRegistrarse.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setMaximumSize(new java.awt.Dimension(152, 36));
        btnRegistrarse.setMinimumSize(new java.awt.Dimension(152, 36));
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        btnCancelar.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(152, 36));
        btnCancelar.setMinimumSize(new java.awt.Dimension(152, 36));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContenidoInferiorLayout = new javax.swing.GroupLayout(ContenidoInferior);
        ContenidoInferior.setLayout(ContenidoInferiorLayout);
        ContenidoInferiorLayout.setHorizontalGroup(
            ContenidoInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrate, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(ContenidoInferiorLayout.createSequentialGroup()
                .addGroup(ContenidoInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoInferiorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoInferiorLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(ContenidoInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblConfContraseña)
                            .addComponent(lblCorreo)
                            .addComponent(lblUsuario)
                            .addComponent(lblContraseña)
                            .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordFieldContraseñaConf, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        ContenidoInferiorLayout.setVerticalGroup(
            ContenidoInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoInferiorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblRegistrate)
                .addGroup(ContenidoInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoInferiorLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(0, 0, 0)
                        .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblUsuario)
                        .addGap(0, 0, 0)
                        .addComponent(TextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblContraseña)
                        .addGap(0, 0, 0)
                        .addComponent(PasswordFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblConfContraseña)
                        .addGap(0, 0, 0)
                        .addComponent(PasswordFieldContraseñaConf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblCorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ContenidoInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(141, 141, 141))
                    .addGroup(ContenidoInferiorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        add(ContenidoInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 410));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
        String nombre = TextFieldNombre.getText();
        String password = PasswordFieldContraseña.getText();
        String correo = TextFieldCorreo.getText();
        
        if ((nombre.isEmpty() || password.isEmpty()) || correo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los datos.");
        }
        if(PasswordFieldContraseñaConf.getText().equals(PasswordFieldContraseña.getText())){
            Cuenta log = new Cuenta();
            log.setVisible(true);
            //inserte método para añadir datos a la BD
            this.dispose();
        }
       
    }//GEN-LAST:event_btnRegistrarseMouseClicked

    private void btnRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseEntered
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnRegistrarseMouseEntered

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        Cuenta log = new Cuenta();
            log.setVisible(true);
            
            this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void TextFieldNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldNombreMouseClicked
        TextFieldNombre.setText("");
        TextFieldNombre.setForeground(black);      
    }//GEN-LAST:event_TextFieldNombreMouseClicked

    private void TextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreActionPerformed

    private void TextFieldUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldUsuarioMouseClicked
        TextFieldUsuario.setText("");
        TextFieldUsuario.setForeground(black);
    }//GEN-LAST:event_TextFieldUsuarioMouseClicked

    private void TextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldUsuarioActionPerformed

    private void TextFieldCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldCorreoFocusLost
             if(isEmail(TextFieldCorreo.getText())){

        }else{
            JOptionPane.showMessageDialog(null, "Correo Electronico incorrecto", "Validar Correo Electronico"
                ,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TextFieldCorreoFocusLost

    private void TextFieldCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldCorreoMouseClicked
            TextFieldCorreo.setText("");
            TextFieldCorreo.setForeground(black);
    }//GEN-LAST:event_TextFieldCorreoMouseClicked

    private void TextFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCorreoActionPerformed

    private void PasswordFieldContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldContraseñaMouseClicked
        PasswordFieldContraseña.setText("");
        PasswordFieldContraseña.setForeground(black);
    }//GEN-LAST:event_PasswordFieldContraseñaMouseClicked

    private void PasswordFieldContraseñaConfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldContraseñaConfMouseClicked
        PasswordFieldContraseñaConf.setText("");
        PasswordFieldContraseñaConf.setForeground(black);
    }//GEN-LAST:event_PasswordFieldContraseñaConfMouseClicked

    private void PasswordFieldContraseñaConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldContraseñaConfActionPerformed

    }//GEN-LAST:event_PasswordFieldContraseñaConfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenidoInferior;
    private javax.swing.JPasswordField PasswordFieldContraseña;
    private javax.swing.JPasswordField PasswordFieldContraseñaConf;
    private javax.swing.JTextField TextFieldCorreo;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldUsuario;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnRegistrarse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConfContraseña;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistrate;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
