/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sis_inf_2;

import java.awt.Color;
import static java.awt.Color.black;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author CORE i5
 */
public class Cuenta extends javax.swing.JPanel {

    private ImageIcon imagen;
    private Icon icono;
    
    public Cuenta() {
        initComponents();
        this.pintarImagen(this.lblImagenPolr, "src/main/java/com/imagenes/polar.jpg");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCorreoTxt = new javax.swing.JLabel();
        textCorreo = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        pnlIngresar = new javax.swing.JPanel();
        lblIngresar = new javax.swing.JLabel();
        pnlCrearCuenta = new javax.swing.JPanel();
        txtCrearCuenta = new javax.swing.JLabel();
        PasswordFieldContraseña = new javax.swing.JPasswordField();
        pnlImagenPolr = new javax.swing.JPanel();
        lblImagenPolr = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Iniciar sesión");

        lblCorreoTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblCorreoTxt.setText("Correo:");

        textCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textCorreoMousePressed(evt);
            }
        });
        textCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCorreoActionPerformed(evt);
            }
        });

        lblContraseña.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblContraseña.setText("Contraseña:");

        pnlIngresar.setBackground(new java.awt.Color(102, 102, 102));
        pnlIngresar.setForeground(new java.awt.Color(255, 255, 255));

        lblIngresar.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        lblIngresar.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresar.setText("INGRESAR");

        javax.swing.GroupLayout pnlIngresarLayout = new javax.swing.GroupLayout(pnlIngresar);
        pnlIngresar.setLayout(pnlIngresarLayout);
        pnlIngresarLayout.setHorizontalGroup(
            pnlIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblIngresar)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlIngresarLayout.setVerticalGroup(
            pnlIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngresar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlCrearCuenta.setBackground(new java.awt.Color(102, 102, 102));
        pnlCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCrearCuentaMouseClicked(evt);
            }
        });

        txtCrearCuenta.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        txtCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        txtCrearCuenta.setText("CREAR CUENTA");

        javax.swing.GroupLayout pnlCrearCuentaLayout = new javax.swing.GroupLayout(pnlCrearCuenta);
        pnlCrearCuenta.setLayout(pnlCrearCuentaLayout);
        pnlCrearCuentaLayout.setHorizontalGroup(
            pnlCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCrearCuentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCrearCuenta)
                .addGap(35, 35, 35))
        );
        pnlCrearCuentaLayout.setVerticalGroup(
            pnlCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCrearCuenta)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PasswordFieldContraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        PasswordFieldContraseña.setForeground(new java.awt.Color(204, 204, 204));
        PasswordFieldContraseña.setText("00000000");
        PasswordFieldContraseña.setBorder(null);
        PasswordFieldContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordFieldContraseñaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordFieldContraseñaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordFieldContraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContraseña)
                            .addComponent(lblCorreoTxt)
                            .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(pnlIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(lblCorreoTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Roboto Slab Thin", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("POLAR TEAM");

        javax.swing.GroupLayout pnlImagenPolrLayout = new javax.swing.GroupLayout(pnlImagenPolr);
        pnlImagenPolr.setLayout(pnlImagenPolrLayout);
        pnlImagenPolrLayout.setHorizontalGroup(
            pnlImagenPolrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImagenPolrLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImagenPolr, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
        );
        pnlImagenPolrLayout.setVerticalGroup(
            pnlImagenPolrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImagenPolrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenPolr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImagenPolrLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlImagenPolr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlImagenPolr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(pnlContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void textCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCorreoActionPerformed

    private void PasswordFieldContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldContraseñaMouseClicked
       
    }//GEN-LAST:event_PasswordFieldContraseñaMouseClicked

    private void pnlCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCrearCuentaMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlCrearCuentaMouseClicked

    private void textCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textCorreoMousePressed
        if(textCorreo.getText().equals("Ingrese su nombre de usuario")){
            textCorreo.setText("");
            textCorreo.setForeground(Color.black);
        } 
        if(String.valueOf(PasswordFieldContraseña.getPassword()).isEmpty()){
            PasswordFieldContraseña.setText("********");
            PasswordFieldContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_textCorreoMousePressed

    private void PasswordFieldContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldContraseñaMousePressed
        if(String.valueOf(PasswordFieldContraseña.getPassword()).equals("********")){
            PasswordFieldContraseña.setText("");
            PasswordFieldContraseña.setForeground(Color.black);
        }
            
        if(textCorreo.getText().isEmpty()){    
            textCorreo.setText("Ingrese su nombre de usuario");
            textCorreo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_PasswordFieldContraseñaMousePressed
    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT
                )
        ); 
        lbl.setIcon(this.icono);
        this.repaint();
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordFieldContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreoTxt;
    private javax.swing.JLabel lblImagenPolr;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlCrearCuenta;
    private javax.swing.JPanel pnlImagenPolr;
    private javax.swing.JPanel pnlIngresar;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JLabel txtCrearCuenta;
    // End of variables declaration//GEN-END:variables

}