/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sis_inf_2;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class pagina1 extends javax.swing.JFrame {

    /**
     * Creates new form pagina1
     */
    public pagina1() {
        initComponents();
    }
    //SARAHI
    public void mostrarPanel(JPanel panel){
        camas.removeAll();
        camas.add(panel);
        camas.revalidate();
        camas.repaint();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        camas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        unaPlaza = new javax.swing.JButton();
        dosPlazas = new javax.swing.JButton();
        tresPlazas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        camas.setBackground(new java.awt.Color(153, 255, 255));
        camas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        jLabel1.setText("                                                                TIPOS DE CAMA ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        unaPlaza.setBackground(new java.awt.Color(0, 102, 102));
        unaPlaza.setText("UNA PLAZA");
        unaPlaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unaPlazaActionPerformed(evt);
            }
        });

        dosPlazas.setBackground(new java.awt.Color(0, 102, 102));
        dosPlazas.setText("DOS PLAZAS");
        dosPlazas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosPlazasActionPerformed(evt);
            }
        });

        tresPlazas.setBackground(new java.awt.Color(0, 102, 102));
        tresPlazas.setText("TRES PLAZAS");

        javax.swing.GroupLayout camasLayout = new javax.swing.GroupLayout(camas);
        camas.setLayout(camasLayout);
        camasLayout.setHorizontalGroup(
            camasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camasLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(camasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unaPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tresPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        camasLayout.setVerticalGroup(
            camasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camasLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(unaPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dosPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tresPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(camas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 680, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unaPlazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unaPlazaActionPerformed
       ventana_produc1 v1 = new ventana_produc1 ();
        v1.setSize(2100, 811);
        v1.setLocation(0, 0);
        camas.removeAll();
        camas.add(v1,BorderLayout.CENTER);
        camas.revalidate();
        camas.repaint();
    }//GEN-LAST:event_unaPlazaActionPerformed

    private void dosPlazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosPlazasActionPerformed
        ventana_produc1 newpantalla =new ventana_produc1 ();
         newpantalla.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_dosPlazasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagina1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagina1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagina1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagina1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagina1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel camas;
    private javax.swing.JButton dosPlazas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tresPlazas;
    private javax.swing.JButton unaPlaza;
    // End of variables declaration//GEN-END:variables
}
